import '../../features/settings/domain/entities/document_settings_entity.dart';

class LanguageHelper {
  static Map<String, String> getTranslations(DocumentLanguage language) {
    switch (language) {
      case DocumentLanguage.english:
        return _english;
      case DocumentLanguage.hindi:
        return _hindi;
      case DocumentLanguage.tamil:
        return _tamil;
      case DocumentLanguage.telugu:
        return _telugu;
      case DocumentLanguage.malayalam:
        return _malayalam;
      case DocumentLanguage.kannada:
        return _kannada;
      case DocumentLanguage.gujarati:
        return _gujarati;
      case DocumentLanguage.marathi:
        return _marathi;
    }
  }

  static const Map<String, String> _english = {
    'taxInvoice': 'TAX INVOICE',
    'billTo': 'Bill To',
    'invoiceDate': 'Invoice Date',
    'dueDate': 'Due Date',
    'item': 'Item',
    'hsn': 'HSN',
    'qty': 'Qty',
    'rate': 'Rate',
    'gst': 'GST%',
    'amount': 'Amount',
    'subtotal': 'Subtotal',
    'discount': 'Discount',
    'taxableAmount': 'Taxable Amount',
    'cgst': 'CGST',
    'sgst': 'SGST',
    'igst': 'IGST',
    'grandTotal': 'Grand Total',
    'notes': 'Notes',
    'termsAndConditions': 'Terms & Conditions',
    'bankDetails': 'Bank Details',
    'bank': 'Bank',
    'accountNumber': 'Account Number',
    'ifscCode': 'IFSC Code',
    'branch': 'Branch',
    'upi': 'UPI',
    'authorizedSignatory': 'Authorized Signatory',
    'signature': 'Signature',
    'gstin': 'GSTIN',
    'phone': 'Phone',
    'email': 'Email',
    'website': 'Website',
  };

  static const Map<String, String> _hindi = {
    'taxInvoice': 'कर चालान',
    'billTo': 'बिल प्राप्तकर्ता',
    'invoiceDate': 'चालान तिथि',
    'dueDate': 'नियत तारीख',
    'item': 'वस्तु',
    'hsn': 'एचएसएन',
    'qty': 'मात्रा',
    'rate': 'दर',
    'gst': 'जीएसटी%',
    'amount': 'राशि',
    'subtotal': 'उप-योग',
    'discount': 'छूट',
    'taxableAmount': 'कर योग्य राशि',
    'cgst': 'सीजीएसटी',
    'sgst': 'एसजीएसटी',
    'igst': 'आईजीएसटी',
    'grandTotal': 'कुल योग',
    'notes': 'टिप्पणियाँ',
    'termsAndConditions': 'नियम और शर्तें',
    'bankDetails': 'बैंक विवरण',
    'bank': 'बैंक',
    'accountNumber': 'खाता संख्या',
    'ifscCode': 'आईएफएससी कोड',
    'branch': 'शाखा',
    'upi': 'यूपीआई',
    'authorizedSignatory': 'अधिकृत हस्ताक्षरकर्ता',
    'signature': 'हस्ताक्षर',
    'gstin': 'जीएसटीआईएन',
    'phone': 'फोन',
    'email': 'ईमेल',
    'website': 'वेबसाइट',
  };

  static const Map<String, String> _tamil = {
    'taxInvoice': 'வரி விலைப்பட்டியல்',
    'billTo': 'பில் பெறுபவர்',
    'invoiceDate': 'விலைப்பட்டியல் தேதி',
    'dueDate': 'செலுத்த வேண்டிய தேதி',
    'item': 'பொருள்',
    'hsn': 'எச்எஸ்என்',
    'qty': 'அளவு',
    'rate': 'விலை',
    'gst': 'ஜிஎஸ்டி%',
    'amount': 'தொகை',
    'subtotal': 'துணை மொத்தம்',
    'discount': 'தள்ளுபடி',
    'taxableAmount': 'வரி விதிக்கத்தக்க தொகை',
    'cgst': 'சிஜிஎஸ்டி',
    'sgst': 'எஸ்ஜிஎஸ்டி',
    'igst': 'ஐஜிஎஸ்டி',
    'grandTotal': 'மொத்த தொகை',
    'notes': 'குறிப்புகள்',
    'termsAndConditions': 'விதிமுறைகள்',
    'bankDetails': 'வங்கி விவரங்கள்',
    'bank': 'வங்கி',
    'accountNumber': 'கணக்கு எண்',
    'ifscCode': 'ஐஎஃப்எஸ்சி குறியீடு',
    'branch': 'கிளை',
    'upi': 'யூபிஐ',
    'authorizedSignatory': 'அங்கீகரிக்கப்பட்ட கையொப்பம்',
    'signature': 'கையொப்பம்',
    'gstin': 'ஜிஎஸ்டிஐஎன்',
    'phone': 'தொலைபேசி',
    'email': 'மின்னஞ்சல்',
    'website': 'இணையதளம்',
  };

  static const Map<String, String> _telugu = {
    'taxInvoice': 'పన్ను ఇన్‌వాయిస్',
    'billTo': 'బిల్ పొందువారు',
    'invoiceDate': 'ఇన్‌వాయిస్ తేదీ',
    'dueDate': 'చెల్లించవలసిన తేదీ',
    'item': 'వస్తువు',
    'hsn': 'హెచ్‌ఎస్‌ఎన్',
    'qty': 'పరిమాణం',
    'rate': 'ధర',
    'gst': 'జిఎస్టి%',
    'amount': 'మొత్తం',
    'subtotal': 'ఉప మొత్తం',
    'discount': 'తగ్గింపు',
    'taxableAmount': 'పన్ను విధించదగిన మొత్తం',
    'cgst': 'సిజిఎస్టి',
    'sgst': 'ఎస్జిఎస్టి',
    'igst': 'ఐజిఎస్టి',
    'grandTotal': 'మొత్తం మొత్తం',
    'notes': 'గమనికలు',
    'termsAndConditions': 'నిబంధనలు మరియు షరతులు',
    'bankDetails': 'బ్యాంక్ వివరాలు',
    'bank': 'బ్యాంక్',
    'accountNumber': 'ఖాతా సంఖ్య',
    'ifscCode': 'ఐఎఫ్‌ఎస్‌సి కోడ్',
    'branch': 'శాఖ',
    'upi': 'యూపిఐ',
    'authorizedSignatory': 'అధికార సంతకం',
    'signature': 'సంతకం',
    'gstin': 'జిఎస్టిఐఎన్',
    'phone': 'ఫోన్',
    'email': 'ఈమెయిల్',
    'website': 'వెబ్‌సైట్',
  };

  static const Map<String, String> _malayalam = {
    'taxInvoice': 'നികുതി ഇൻവോയ്സ്',
    'billTo': 'ബിൽ സ്വീകരിക്കുന്നവർ',
    'invoiceDate': 'ഇൻവോയ്സ് തീയതി',
    'dueDate': 'അവസാന തീയതി',
    'item': 'ഇനം',
    'hsn': 'എച്ച്എസ്എൻ',
    'qty': 'അളവ്',
    'rate': 'നിരക്ക്',
    'gst': 'ജിഎസ്ടി%',
    'amount': 'തുക',
    'subtotal': 'ഉപ ആകെ',
    'discount': 'കിഴിവ്',
    'taxableAmount': 'നികുതി നൽകേണ്ട തുക',
    'cgst': 'സിജിഎസ്ടി',
    'sgst': 'എസ്ജിഎസ്ടി',
    'igst': 'ഐജിഎസ്ടി',
    'grandTotal': 'മൊത്തം തുക',
    'notes': 'കുറിപ്പുകൾ',
    'termsAndConditions': 'നിബന്ധനകളും വ്യവസ്ഥകളും',
    'bankDetails': 'ബാങ്ക് വിശദാംശങ്ങൾ',
    'bank': 'ബാങ്ക്',
    'accountNumber': 'അക്കൗണ്ട് നമ്പർ',
    'ifscCode': 'ഐഎഫ്എസ്സി കോഡ്',
    'branch': 'ശാഖ',
    'upi': 'യുപിഐ',
    'authorizedSignatory': 'അംഗീകൃത ഒപ്പ്',
    'signature': 'ഒപ്പ്',
    'gstin': 'ജിഎസ്ടിഐഎൻ',
    'phone': 'ഫോൺ',
    'email': 'ഇമെയിൽ',
    'website': 'വെബ്സൈറ്റ്',
  };

  static const Map<String, String> _kannada = {
    'taxInvoice': 'ತೆರಿಗೆ ಇನ್‌ವಾಯ್ಸ್',
    'billTo': 'ಬಿಲ್ ಸ್ವೀಕರಿಸುವವರು',
    'invoiceDate': 'ಇನ್‌ವಾಯ್ಸ್ ದಿನಾಂಕ',
    'dueDate': 'ಕೊನೆಯ ದಿನಾಂಕ',
    'item': 'ವಸ್ತು',
    'hsn': 'ಎಚ್‌ಎಸ್‌ಎನ್',
    'qty': 'ಪ್ರಮಾಣ',
    'rate': 'ದರ',
    'gst': 'ಜಿಎಸ್ಟಿ%',
    'amount': 'ಮೊತ್ತ',
    'subtotal': 'ಉಪ ಒಟ್ಟು',
    'discount': 'ರಿಯಾಯಿತಿ',
    'taxableAmount': 'ತೆರಿಗೆ ವಿಧಿಸಬಹುದಾದ ಮೊತ್ತ',
    'cgst': 'ಸಿಜಿಎಸ್ಟಿ',
    'sgst': 'ಎಸ್ಜಿಎಸ್ಟಿ',
    'igst': 'ಐಜಿಎಸ್ಟಿ',
    'grandTotal': 'ಒಟ್ಟು ಮೊತ್ತ',
    'notes': 'ಟಿಪ್ಪಣಿಗಳು',
    'termsAndConditions': 'ನಿಯಮಗಳು ಮತ್ತು ಷರತ್ತುಗಳು',
    'bankDetails': 'ಬ್ಯಾಂಕ್ ವಿವರಗಳು',
    'bank': 'ಬ್ಯಾಂಕ್',
    'accountNumber': 'ಖಾತೆ ಸಂಖ್ಯೆ',
    'ifscCode': 'ಐಎಫ್‌ಎಸ್‌ಸಿ ಕೋಡ್',
    'branch': 'ಶಾಖೆ',
    'upi': 'ಯುಪಿಐ',
    'authorizedSignatory': 'ಅಧಿಕೃತ ಸಹಿ',
    'signature': 'ಸಹಿ',
    'gstin': 'ಜಿಎಸ್ಟಿಐಎನ್',
    'phone': 'ದೂರವಾಣಿ',
    'email': 'ಇಮೇಲ್',
    'website': 'ವೆಬ್‌ಸೈಟ್',
  };

  static const Map<String, String> _gujarati = {
    'taxInvoice': 'કર ઇનવોઇસ',
    'billTo': 'બિલ પ્રાપ્તકર્તા',
    'invoiceDate': 'ઇનવોઇસ તારીખ',
    'dueDate': 'અંતિમ તારીખ',
    'item': 'વસ્તુ',
    'hsn': 'એચએસએન',
    'qty': 'જથ્થો',
    'rate': 'દર',
    'gst': 'જીએસટી%',
    'amount': 'રકમ',
    'subtotal': 'પેટા કુલ',
    'discount': 'છૂટ',
    'taxableAmount': 'કરપાત્ર રકમ',
    'cgst': 'સીજીએસટી',
    'sgst': 'એસજીએસટી',
    'igst': 'આઈજીએસટી',
    'grandTotal': 'કુલ રકમ',
    'notes': 'નોંધો',
    'termsAndConditions': 'નિયમો અને શરતો',
    'bankDetails': 'બેંક વિગતો',
    'bank': 'બેંક',
    'accountNumber': 'ખાતા નંબર',
    'ifscCode': 'આઈએફએસસી કોડ',
    'branch': 'શાખા',
    'upi': 'યુપીઆઈ',
    'authorizedSignatory': 'અધિકૃત હસ્તાક્ષર',
    'signature': 'હસ્તાક્ષર',
    'gstin': 'જીએસટીઆઈએન',
    'phone': 'ફોન',
    'email': 'ઈમેલ',
    'website': 'વેબસાઈટ',
  };

  static const Map<String, String> _marathi = {
    'taxInvoice': 'कर चलन',
    'billTo': 'बिल प्राप्तकर्ता',
    'invoiceDate': 'चलन तारीख',
    'dueDate': 'अंतिम तारीख',
    'item': 'वस्तू',
    'hsn': 'एचएसएन',
    'qty': 'प्रमाण',
    'rate': 'दर',
    'gst': 'जीएसटी%',
    'amount': 'रक्कम',
    'subtotal': 'उप एकूण',
    'discount': 'सूट',
    'taxableAmount': 'करपात्र रक्कम',
    'cgst': 'सीजीएसटी',
    'sgst': 'एसजीएसटी',
    'igst': 'आयजीएसटी',
    'grandTotal': 'एकूण रक्कम',
    'notes': 'टिपा',
    'termsAndConditions': 'अटी व शर्ती',
    'bankDetails': 'बँक तपशील',
    'bank': 'बँक',
    'accountNumber': 'खाते क्रमांक',
    'ifscCode': 'आयएफएससी कोड',
    'branch': 'शाखा',
    'upi': 'युपीआय',
    'authorizedSignatory': 'अधिकृत स्वाक्षरी',
    'signature': 'स्वाक्षरी',
    'gstin': 'जीएसटीआयएन',
    'phone': 'फोन',
    'email': 'ईमेल',
    'website': 'वेबसाइट',
  };
}

