// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGMfUtvLNYJeoWU_M8VGeiFs3X0wG2BNY',
    appId: '1:1029956896999:web:05b380eeb975817543fa42',
    messagingSenderId: '1029956896999',
    projectId: 'billing-87872',
    authDomain: 'billing-87872.firebaseapp.com',
    storageBucket: 'billing-87872.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE5MW9zlm7kgJwbz6NvxiNTLP595Yiyck',
    appId: '1:1029956896999:android:2bbd14e26a6972ac43fa42',
    messagingSenderId: '1029956896999',
    projectId: 'billing-87872',
    storageBucket: 'billing-87872.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPdfLNwEEIHwlCDk-L-3fFeVWUYjIJSmI',
    appId: '1:1029956896999:ios:1444143ff5aaf7c943fa42',
    messagingSenderId: '1029956896999',
    projectId: 'billing-87872',
    storageBucket: 'billing-87872.firebasestorage.app',
    iosBundleId: 'com.example.billingManagement',
  );
}
