// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCffW1ayDe4TICsjWghGhaEtrfigKoBYjk',
    appId: '1:557515558673:web:ec6aeb3f70c22a25c7c6b0',
    messagingSenderId: '557515558673',
    projectId: 'gst-billing-477306',
    authDomain: 'gst-billing-477306.firebaseapp.com',
    storageBucket: 'gst-billing-477306.firebasestorage.app',
    measurementId: 'G-YVDGQ4N5CV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClstt2kbBZz6xJFYmELqDUJ2Kq9efgvMU',
    appId: '1:557515558673:android:57dff98decc0b4a9c7c6b0',
    messagingSenderId: '557515558673',
    projectId: 'gst-billing-477306',
    storageBucket: 'gst-billing-477306.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZjOw7wPF1_qQAEK9OUh373rPB39tgG4o',
    appId: '1:557515558673:ios:4dbffcff62b186bbc7c6b0',
    messagingSenderId: '557515558673',
    projectId: 'gst-billing-477306',
    storageBucket: 'gst-billing-477306.firebasestorage.app',
    androidClientId: '557515558673-6f7i2tnpmgsofm2av1pu1qdkc79ajb2j.apps.googleusercontent.com',
    iosClientId: '557515558673-b1i93imert50r09f99rfp27agbpegb2s.apps.googleusercontent.com',
    iosBundleId: 'com.example.billingManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZjOw7wPF1_qQAEK9OUh373rPB39tgG4o',
    appId: '1:557515558673:ios:4dbffcff62b186bbc7c6b0',
    messagingSenderId: '557515558673',
    projectId: 'gst-billing-477306',
    storageBucket: 'gst-billing-477306.firebasestorage.app',
    androidClientId: '557515558673-6f7i2tnpmgsofm2av1pu1qdkc79ajb2j.apps.googleusercontent.com',
    iosClientId: '557515558673-b1i93imert50r09f99rfp27agbpegb2s.apps.googleusercontent.com',
    iosBundleId: 'com.example.billingManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCffW1ayDe4TICsjWghGhaEtrfigKoBYjk',
    appId: '1:557515558673:web:83a95dfe19d95917c7c6b0',
    messagingSenderId: '557515558673',
    projectId: 'gst-billing-477306',
    authDomain: 'gst-billing-477306.firebaseapp.com',
    storageBucket: 'gst-billing-477306.firebasestorage.app',
    measurementId: 'G-4P3C2T9N8H',
  );

}